# Generated by Django 5.0.1 on 2025-01-18 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenthx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communication',
            old_name='communication',
            new_name='communication_text',
        ),
        migrations.RemoveField(
            model_name='job',
            name='communications',
        ),
        migrations.AddField(
            model_name='communication',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenthx.job'),
        ),
    ]
