# Generated by Django 5.0.1 on 2025-01-18 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenthx', '0002_rename_communication_communication_communication_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenthx.job'),
        ),
    ]
